import { ui, scoreColor, severityColor, progressBar, logo, box } from './ui.mjs';

export function formatScan(scan) {
  const score = scoreColor(scan.score, `${scan.score}/100`);
  const status = scoreColor(scan.score, scan.label.toUpperCase());
  const metrics = `${scan.metrics.codeFiles} source · ${scan.metrics.testFiles} tests · ${scan.metrics.loc.toLocaleString()} LOC`;
  const lines = [
    logo(),
    '',
    box('Vibe Health', [
      `${progressBar(scan.score)}  ${ui.bold(score)}  ${status}`,
      ui.dim(metrics),
      `Stack  ${scan.stack.join(' · ') || 'unknown'}`
    ])
  ];

  if (!scan.findings.length) {
    lines.push('', `${ui.green('✓')} ${ui.bold('No major repository-health risks detected.')}`);
  } else {
    lines.push('', ui.bold(`Findings (${scan.findings.length})`));
    for (const finding of scan.findings) {
      const tag = severityColor(finding.severity, finding.severity.toUpperCase().padEnd(8));
      lines.push(`  ${tag} ${ui.bold(finding.code)}  ${finding.message}`);
    }
  }

  if (scan.largeFiles.length) {
    lines.push('', ui.bold('High-friction files'));
    for (const item of scan.largeFiles.slice(0, 6)) lines.push(`  ${ui.yellow('•')} ${item.file} ${ui.dim(`(${item.loc} LOC)`)}`);
  }

  lines.push('', ui.dim('Tip: run `vibe-surgeon guard . --base origin/main` before merging.'));
  return lines.join('\n');
}

export function formatGuard(result) {
  const color = result.level === 'high' ? ui.red : result.level === 'medium' ? ui.yellow : ui.green;
  const symbol = result.pass ? '✓' : '✕';
  const rows = [
    `${color(symbol)} Risk ${color(result.level.toUpperCase())} · ${result.risk}/100`,
    `${result.changed.length} changed · ${result.impacted.length} impacted · ${result.impactedTests.length} impacted tests`
  ];
  if (result.reasons.length) rows.push(...result.reasons.map((x) => `• ${x}`));
  return `${logo()}\n\n${box('Change Guard', rows)}`;
}

export function formatBaseline(result) {
  if (!result.exists) return `${ui.yellow('!')} ${result.message}`;
  const delta = result.scoreDelta > 0 ? `+${result.scoreDelta}` : String(result.scoreDelta);
  const color = result.regressed ? ui.red : result.scoreDelta > 0 ? ui.green : ui.cyan;
  const rows = [
    `Baseline ${result.baseline.score}/100 → now ${result.scan.score}/100  ${color(delta)}`,
    `New findings: ${result.introduced.join(', ') || 'none'}`,
    `Resolved: ${result.resolved.join(', ') || 'none'}`,
    result.regressed ? ui.red('Regression detected') : ui.green('No safety regression detected')
  ];
  return box('Baseline Diff', rows);
}

export function doctorMarkdown(scan, graph) {
  const severityOrder = { critical: 0, high: 1, medium: 2, low: 3 };
  const findings = [...scan.findings].sort((a, b) => severityOrder[a.severity] - severityOrder[b.severity]);
  const tasks = findings.map((f, i) => `- [ ] P${severityOrder[f.severity]}-${String(i + 1).padStart(2, '0')} **${f.code}** — ${f.message}`);
  const hotspotRows = graph.hotspots.slice(0, 10).map((h) => `| \`${h.file}\` | ${h.inbound} | ${h.outbound} | ${h.score} |`).join('\n');

  return `# Vibe Surgeon — Repair Plan\n\nGenerated: ${scan.generatedAt}\n\n## Health\n\n- Score: **${scan.score}/100 (${scan.label})**\n- Stack: ${scan.stack.join(', ') || 'unknown'}\n- Source LOC: ${scan.metrics.loc}\n- Tests detected: ${scan.metrics.testFiles}\n\n## Priority backlog\n\n${tasks.join('\n') || '- [x] No major findings.'}\n\n## Hotspots\n\n| File | Inbound deps | Outbound deps | Risk score |\n|---|---:|---:|---:|\n${hotspotRows || '| — | 0 | 0 | 0 |'}\n\n## Agent repair protocol\n\n1. Work on one backlog item at a time.\n2. Before editing a hotspot, inspect callers and nearby tests.\n3. Do not delete unrelated behavior to make tests pass.\n4. Add or update tests before large refactors.\n5. Run Vibe Surgeon guard before commit.\n`;
}

export function architectureMarkdown(scan, graph) {
  const hotspots = graph.hotspots.slice(0, 15).map((h) => `- \`${h.file}\` — inbound ${h.inbound}, outbound ${h.outbound}`).join('\n');
  return `# Repository Map\n\nGenerated by Vibe Surgeon.\n\n## Stack\n\n${scan.stack.map((x) => `- ${x}`).join('\n') || '- Unknown'}\n\n## Scale\n\n- ${graph.nodes.length} importable source files\n- ${graph.edges.length} local dependency edges\n- ${scan.metrics.loc} source LOC\n\n## Hotspots\n\n${hotspots || '- No dependency hotspots found.'}\n\n## Notes\n\nThis map focuses on local file-to-file dependencies. Package imports and runtime service calls are not treated as proven dependencies.\n`;
}
